branch-defaults:
  PV-17:
    environment: PathfindingVisualizer
    group_suffix: null
  default:
    environment: PathfindingVisualizer
    group_suffix: null
global:
  application_name: PathfinderVisualizer
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
